name: Deploy JSD
on:
  push:
    tags:
      - 'JSD*'
jobs:
  deploy-jsd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Node version ğŸ“¦
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'
          check-latest: true

      - name: Install and Build ğŸ”§
        run: |
          yarn
          yarn lerna run --scope '@shared/**' build
          yarn lerna bootstrap
          yarn workspace @websites/jsd build

      - name: Deploy ğŸš€
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=./@websites/jsd/build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_JSD_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
