name: Deploy lessons to S3
run-name: ${{ github.actor }} is deploying lessons to S3
on:
  push:
    # branches:
    #   - main
    paths:
      - .github/workflows/deploy-lessons.yml
      - lessons/src/lessons
jobs:
  deploy-lesson-to-s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.7.4

      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: pnpm

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::083014415996:role/github_actions_role
          aws-region: us-east-1

      - name: Install dependencies ğŸ“¦
        run: pnpm install

      - name: Publish lessons to S3
        run: pnpm nx run lessons:publish
